Update mysql settings and remove unsupported systems
artefactual/deploy-pub pull request #107
Opened 2019-06-07 00:37 UTC by scollazo

2019-06-07 21:41 UTC, DavidHume-ArtefactualSystems requested changes
Shouldn't playbooks/atom-bionic/ also have a README.md?

Otherwise, looks good!

2019-06-10 21:52 UTC, djjuhasz approved these changes
Looks good to me. 👍

2019-07-01 10:06 UTC, scollazo commented
@DavidHume-ArtefactualSystems README file added

2019-07-02 20:00 UTC, DavidHume-ArtefactualSystems approved these changes

2019-07-03 19:46 UTC, merged