Add packer configs
artefactual/deploy-pub pull request #31
Opened 2017-04-28 09:44 UTC by scollazo

Packer configurations have been living in a private repo, I want to add them to deploy-pub

This pr has the git history for the record, but I would prefer to merge it using only one commit

2017-04-28 15:31 UTC, sevein approved these changes

2017-04-28 17:34 UTC, sevein requested changes
I agree best to squash all the commits into one. The commits you brought are empty, that would only confuse users.

2017-04-28 18:37 UTC, scollazo commented
After talking with @jhsimpson , he thinks this might be part of am-packbuild, instead of deploy-pub, as this repo should be only for playbooks.

2017-05-01 19:21 UTC, scollazo commented
Closed no behalf of https://github.com/artefactual-labs/am-packbuild/pull/40

2017-05-01 19:21 UTC, closed without merging