playbooks/archivematica: install openjdk instead of oracle java
artefactual/deploy-pub pull request #47
Opened 2017-10-19 18:28 UTC by hakamine

Oracle repository seems to be no longer providing the
oracle-java8-installer package required by the
ansible-elasticsearch role. Install openjdk 7
provided by Ubuntu trusty standard repository instead.
Ref. https://github.com/artefactual-labs/ansible-elasticsearch/issues/3

2017-10-19 20:44 UTC, sevein approved these changes
@hakamine I was wondering if we should be doing the same change on the playbooks/archivematica-xenial/vars-singlenode-1.6.yml document?

2017-10-19 20:45 UTC, sevein requested changes
Sorry I meant to click on the "request changes" button on my previous review.

2017-10-20 16:36 UTC, mamedin commented
Yesterday I was deploying some sites using the ansible extra-var "elasticsearch_apt_java_package=openjdk-7-jre-headless" and it works fine.

2017-10-20 17:15 UTC, scollazo commented
I would prefer using default-jdk-headless instead of a version number, because this way the same package work on trusty and xenial. 

The /usr/lib/jvm/default-java link seems to be created when you install any openjdk package.

2017-10-20 17:16 UTC, scollazo submitted a review, later dismissed
I would prefer using default-jdk-headless instead of a version number, because this way the same package work on trusty and xenial. 

The /usr/lib/jvm/default-java link seems to be created when you install any openjdk package

2017-10-20 17:26 UTC, mamedin commented
I'm agree with Santi, it's better using a metapackage, but the metapackage's name I think that is default-jre-headless.

2017-10-20 17:57 UTC, sevein commented
I vote for the current approach because explicit > implicit.
Duplication is boring but it's safe.

2017-10-20 19:21 UTC, hakamine commented
I added a commit with changes to playbook/archivematica-xenial. In xenial, using openjdk-8-headless instead of 7

2017-10-20 19:23 UTC, sevein approved these changes
👍

2017-10-20 19:30 UTC, merged

2017-10-20 19:37 UTC, sevein commented
@sbreker ^ ^