Update to stable/1.7.x
artefactual/deploy-pub pull request #52
Opened 2018-01-31 01:57 UTC by scollazo

Instead of using a shared folder for deployment, this PR changes that and uses the default archivematica directory (/opt/archivematica)

Also, instead of mounting the current path as /vagrant, mount it as /home/vagrant-sync. This way, it can be used as a transfer source (because it is under /home), and allows users to test archivematica with their own files.

2018-01-31 02:12 UTC, scollazo commented
Related to artefactua/deploy-pub#51

2018-01-31 02:18 UTC, scollazo commented
I think that changing the path to the archivematica clone in order to avoid the virtualbox shared folder,  will fix artefactual/deploy-pub#22 , and help with windows support ( artefactual/deploy-pub#40)

2018-01-31 16:49 UTC, hakamine commented
I think the main reason to put the archivematica code in a synced folder was to allow developers to easily modify the code from the host (which is a big plus for development). If the code is now deployed to /opt/archivematica and this folder is not synced this feature will be lost.

2018-02-06 15:50 UTC, scollazo commented
The problem is that the npm package have problems to install/build. I think this happens because they need a lot of different files, and the vbox driver is not able to handle that in a timely fashion, and that affects all users, developers or not.

We should look for other ways to share the source between the host and the vm

2018-02-06 17:00 UTC, sevein reviewed
I'd suggest to address the changes around synced folders separately. This would mean giving up on deploy-pub as a development workflow - is that what we want? Should we file an issue and consult the team/community beforehand? Perhaps we should have a `playbooks/archivematica-development` playbook?

This PR could remain as the changeset suggested to update the branch requirements of the roles and the changes around the indexless feature.

2018-02-06 17:29 UTC, jrwdunham commented
Should the `archivematica_src_search_enabled` var be in the vars-singlenode-x.yml files with a default "yes" value? Also, as with the ansible role PR, should we document this new variable and the indexless option in the README here too?

2018-02-06 18:07 UTC, jhsimpson commented
This might not be a relevant comment, but does part of the problem come from the need to build the javascript apps with node on the server Archivematica is being deployed to?  In the past, the appraisal tab and transfer browser components were built manually using webpack, and so there were fewer build dependencies required during deployment.  

If the node apps where built and stored in an registry or artifact repository somewhere, would that make the deploy faster and work with fewer dependencies?

2018-02-06 20:09 UTC, sevein commented
How much faster do you want it to be? I can manually 1) clone the repo, 2) build appraisal-tab and 3) build transfer-browser in about a minute. I've uploaded a little asciinema so you have an idea how fast this stuff got in the last year: https://asciinema.org/a/ibpqExMCCJiQKPwBXWR5kMMJD. Building with yarn seems a tiny bit faster but it's almost unnoticeable. And if we merged transfer-browser and appraisal-tab as a single front-end project then we would cut the build time in half.

For some perspective, `lxml` alone takes 1 minute and 20 seconds to build. We build it four times (MCPServer/MCPClient/Dashboard/StorageService).

The problem with the Dashboard front-end build that Santi is trying to fix is only reproducible when you're using VirtualBox + `vboxsf` shared folders. We could arrange things in this repo so `vboxsf` is only used by a new `playbooks/archivematica-dev` environment where we also ask the developer to run `npm install` manually.

For deployments, deb/rpm packages and our Docker image already bundles the front-end prebuilts. I think that it'd be ok if we continue letting Ansible build all the things from the scratch, it makes things simpler for us.

2018-02-06 20:13 UTC, scollazo commented
Does this work on the vagrant environment, using a shared folder for archivematica?

>How much faster do you want it to be? I can manually 1) clone the repo, 2) build appraisal-tab and 3) build transfer-browser in about a minute.

2018-02-06 20:19 UTC, sevein commented
> Does this work on the vagrant environment, using a shared folder for archivematica?

No. But I think that this could be considered a minor issue iff we only used vboxsf in development environments (e.g. `playbooks/archivematica-dev`?). We would also have to tell developers to avoid running `npm install` inside the virtual machine but run it from the host instead.

2018-02-06 20:20 UTC, scollazo commented
> Should the archivematica_src_search_enabled var be in the vars-singlenode-x.yml files with a default "yes" value? Also, as with the ansible role PR, should we document this new variable and the indexless option in the README here too?

The current docs point to the defaults/main.yml, not sure why this case requires to be added in a explicit way

2018-02-06 20:22 UTC, scollazo commented
@sevein we have ```archivematica_src_environment_type``` that defaults to production, but is overrided in the vagrantfile with ```development```

I think we should use the default value when building from vagrant, and set to "development" when needed. When this "development" mode is enabled, we won't build npm dependencies.

What do you think?

2018-02-06 20:23 UTC, sevein commented
Sounds like a good plan.

2018-02-07 16:45 UTC, sevein commented on playbooks/archivematica-xenial/Vagrantfile
> +  config.vm.synced_folder '.', '/home/vagrant-sync'
IIRC `/vagrant` is a default synced folder configured by Vagrant and the original L34 wasn't really needed. I think that what this means is that with your change you would have a new `/home/vagrant-sync` but `/vagrant` would still be configured automatically. I haven't confirmed it but I have a strong feeling that this is the case.

If you wanted to disable `/vagrant` I think that you'd need to add the additional line:

    config.vm.synced_folder ".", "/vagrant", disabled: true

In any case, I'd still recommend to submit this as a separate issue/pull-request.

2018-02-08 18:21 UTC, scollazo commented
Created https://github.com/artefactual-labs/ansible-archivematica-src/pull/173 to circunvent the issue with vagrant and shared folders

2018-02-11 23:52 UTC, jrwdunham commented
>> Should the archivematica_src_search_enabled var be in the vars-singlenode-x.yml files with a default "yes" value? Also, as with the ansible role PR, should we document this new variable and the indexless option in the README here too?

> The current docs point to the defaults/main.yml, not sure why this case requires to be added in a explicit way

But you're talking about https://github.com/artefactual-labs/ansible-archivematica-src/tree/qa/1.7.x, right? I mean, in this repo and this PR we only mention the `archivematica_src_search_enabled` var twice, once in playbooks/archivematica/singlenode.yml and the other time in playbooks/archivematica-xenial/singlenode.yml. 

It seems to me, that in order to make it easy for an end user of this repo to deploy AM without indexing, we should have `archivematica_src_search_enabled: "no"` in the following:

- playbooks/archivematica-xenial/vars-singlenode-1.7.yml
- playbooks/archivematica/vars-singlenode-1.7.yml

2018-02-14 00:14 UTC, jrwdunham commented
@scollazo @sevein can we make some movement on this? It's becoming a blocker for the Columbia work.

2018-02-14 00:28 UTC, jrwdunham commented
Oops, I didn't mean to close this issue.

I deployed AM on Ubuntu 14 using this branch and dev/allow-indexless-install (now qa/1.7.x) of ansible-archivematica-src and confirmed that it can create a headless deploy of AM that passes the relevant acceptance tests. See https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/67#issuecomment-365447477.

I don't know about the synced folder/NPM issue but from the POV of deploying ES-less AM, this is good to merge IMO.

2018-02-14 16:09 UTC, scollazo commented
The pr has been remade, and splitted into more meaningful commits

I'm not sure if we should set the indexless install as the default one, or as an option to be chosen by the user.

2018-02-14 17:16 UTC, sevein requested changes
Can you update the description of the PR? I think that the current description is not describing all the changes that you're making.  I just want to make sure that when someone lands into this PR it's easier to see what changes are happening and why.

Also, the development workflow changes considerably, i.e.:
1) The developer needs to change the environment type variable (`archivematica_src_environment_type`) to `development`,
2) The developer needs to assign the `/vagrant/src/`  value to `archivematica_src_dir`,
3) The developer needs to run `npm install` manually from the host.

Should this be added to the README?

2018-02-14 17:16 UTC, sevein commented on playbooks/archivematica-centos7/singlenode.yml
> +   - name: "Selinux boolean 1"
Could this be more descriptive?
e.g. `SELinux: allow HTTPD scripts and modules to connect to the network.`

Same with the others.

2018-02-14 17:16 UTC, sevein commented on playbooks/archivematica-centos7/singlenode.yml
> +       ports: 8000,8001
Do you want to quote this so it's consistent with our style of writing YAML files? It's definitely a string.

2018-02-14 17:16 UTC, sevein commented on playbooks/archivematica-centos7/singlenode.yml
> +   - name: "Enable epel repository"
`s/epel/EPEL`

2018-02-14 18:22 UTC, sevein requested changes
What do you think about these notes for the README in regards to the development workflow? https://gist.github.com/sevein/74f26cf6638ff19276e2808c152faf71

2018-02-15 15:14 UTC, scollazo commented
I'm testing a fix for the root cause, adding ```config.vm.synced_folder '.', '/vagrant',mount_options: ["uid=333", "gid=333"]``` to the vagrant file configuration may be the key to the npm problem.

If it works, I'll push 
https://github.com/artefactual/deploy-pub/compare/dev/update-to-1.7-take3 to this pr

2018-02-15 15:54 UTC, scollazo commented
Tested with trusty, and npm works.

Also, a pull request removing the workaround in the archivematica ansible role that should be merged for this to work, has been created at https://github.com/artefactual-labs/ansible-archivematica-src/pull/174

2018-02-15 16:31 UTC, sevein requested changes

2018-02-15 16:31 UTC, sevein commented on playbooks/archivematica-centos7/Vagrantfile
> +  config.vm.synced_folder '.', '/vagrant',mount_options: ["uid=333", "gid=333"]
Whitespace after the comma?

2018-02-15 16:35 UTC, sevein requested changes
The description of the PR is outdated.

My comments have not been addressed yet.

2018-02-15 17:53 UTC, scollazo commented
@sevein your feedback has been addresed. Regarding your gist, I would prefer to merge this "as is", and make the doc update changes as part of a fix to #53

2018-02-15 18:09 UTC, sevein requested changes

2018-02-15 18:09 UTC, sevein commented on playbooks/archivematica/vars-singlenode-1.7.yml
> +# elasticsearch role
Cosmetic change: missing blank line before L13.

2018-02-15 18:09 UTC, sevein commented on playbooks/archivematica-centos7/Vagrantfile
> +  config.vm.synced_folder '.', '/vagrant',mount_options: ["uid=333","gid=333"]
Whitespace after comma.

2018-02-15 18:09 UTC, sevein commented on playbooks/archivematica-centos7/singlenode.yml
> +   - name: "SELinux: Allow nginx connections to gunicorn"
s/gunicorn/Gunicorn

2018-02-15 18:09 UTC, sevein commented on playbooks/archivematica-centos7/singlenode.yml
> +   - name: "SELinux: Allow nginx to connect to mysql "
- s/mysql/MySQL
- whitespace before `"`

2018-02-15 18:09 UTC, sevein commented on playbooks/archivematica/Vagrantfile
> +  config.vm.synced_folder '.', '/vagrant',mount_options: ["uid=333","gid=333"]
Missing whitespace after comma.

2018-02-15 18:13 UTC, sevein commented on playbooks/archivematica-centos7/Vagrantfile
> +  config.vm.synced_folder '.', '/vagrant',mount_options: ["uid=333","gid=333"]
Cosmetic: `config.vm.synced_folder '.', '/vagrant', mount_options: ["uid=333", "gid=333"]`

2018-02-15 18:34 UTC, sevein approved these changes

2018-02-15 18:37 UTC, merged

2018-02-15 20:50 UTC, jrwdunham commented
@sevein I like your proposed additions to the README. I don't want to have to re-remember these things if I have to create a new ansible/vagrant dev deploy again some day.

2018-02-15 20:51 UTC, sevein commented
> @sevein I like your proposed additions to the README. I don't want to have to re-remember these things if I have to create a new ansible/vagrant dev deploy again some day.

I'll submit a PR soon!