Dev/centos7 fixes percona
artefactual/deploy-pub pull request #89
Opened 2018-08-30 12:59 UTC by mamedin

These changes connect to issues #83 and #82 and add the following changes:

*The artefactual ansible-gearman role is used.
*The artefactual ansible-percona role is used
* The artefactual ansible-nginx role is used
* `libsemanage-python`, `policycoreutils-python` are installed (SELinux dependencies)

Using these roles makes this playbook practically identical to Ubuntu playbooks, except for the pre-task that configures SELinux when it is active.

2018-09-04 11:00 UTC, jhsimpson commented
I tested this on a RHEL 7.5 server and it did not work.  Some tweaks are required to support both CentOS and RHEL with these changes.

2018-09-05 14:03 UTC, scollazo requested changes

2018-09-05 14:03 UTC, scollazo commented on playbooks/archivematica-centos7/requirements.yml
> +  version: "dev/centos-support"
We should merge dev/centos-support branch into master, instead of using custom branches

2018-09-07 15:47 UTC, sevein approved these changes

2018-09-07 15:55 UTC, merged