playbooks: add Ubuntu bionic playbook
artefactual/deploy-pub pull request #90
Opened 2018-08-31 15:10 UTC by scollazo

This references archivematica/Issues#119

2018-08-31 21:56 UTC, mamedin requested changes
The bionic-support commit in SS stable/0.11.x is missing and thus we can finish the test.

2018-08-31 21:56 UTC, mamedin commented on playbooks/archivematica-bionic/vars-singlenode-1.6.yml
> +---
I think this file is not needed. There are no support for bionic on AM 1.6

2018-08-31 21:59 UTC, sevein requested changes
You may want to ignore this one too:

    playbooks/archivematica-bionic/ubuntu-bionic-18.04-cloudimg-console.log

2018-09-05 16:15 UTC, scollazo commented
Removed `playbooks/archivematica-bionic/ubuntu-bionic-18.04-cloudimg-console.log` and vars-singlenode-1.6.yml

2018-09-05 16:35 UTC, sevein commented on playbooks/archivematica-bionic/.gitignore
> +/ubuntu-xenial-16.04-cloudimg-console.log
Shouldn't this entry be different? `/ubuntu-bionic-18.04-cloudimg-console.log`?

2018-09-05 16:36 UTC, sevein commented on playbooks/archivematica-bionic/README.md
> +
Is ^ outdated?

2018-09-05 16:37 UTC, sevein commented on playbooks/archivematica-bionic/Vagrantfile
> +      "ip" => "192.168.168.196",
We've been allocating unique IPs for the different playbooks/****** environments, should the value here be different too?

2018-09-05 18:25 UTC, scollazo commented on playbooks/archivematica-bionic/README.md
> +
Updated, but we'll have to update it again once the stable/0.12.x branch is created

2018-09-05 18:25 UTC, scollazo commented on playbooks/archivematica-bionic/Vagrantfile
> +      "ip" => "192.168.168.196",
Use 192.168.168.198

2018-09-05 18:25 UTC, scollazo commented on playbooks/archivematica-bionic/.gitignore
> +/ubuntu-xenial-16.04-cloudimg-console.log
Fixed

2018-09-05 18:33 UTC, sevein approved these changes

2018-09-05 21:38 UTC, scollazo commented
Merged as 85d10321aacb86bf24e2ff06ec465c75c99bae75

2018-09-05 21:38 UTC, closed without merging